### ISSUE TITLE
Kontakt oldal

### ISSUE THREAD

**Issue by baracskaidora** [baracskaidora/Proj1-elements-9C#11]

**Comment by prumullertamas** [comment]
<a href="mailto:webmaster@example.com">Jon Doe</a>

**Comment by prumullertamas** [comment]
<a href="mailto:webmaster@example.com">Jon Doe</ah>

**Comment by prumullertamas** [comment]
<a href="mailto:webmaster@example.com">Jon Doe aztán végső tag
