### ISSUE TITLE
Össze kéne hozni az oldalakat meg karuzelt csinálni

### ISSUE THREAD

**Issue by prumullertamas** [baracskaidora/Proj1-elements-9C#14]
Ja most ezzel kell foglalkozni

**Comment by prumullertamas** [comment]
![erdoe](https://user-images.githubusercontent.com/122269855/220084978-24eeb148-3834-42d9-a480-c109a45e5993.png)
![jeg](https://user-images.githubusercontent.com/122269855/220084981-2ed78abf-ca68-42da-af78-691f690a575a.png)
![feny](https://user-images.githubusercontent.com/122269855/220084982-4fc540d2-6055-49b6-aa1c-c9121c7764c9.png)
<img width="596" alt="kristaly" src="https://user-images.githubusercontent.com/122269855/220084985-b35fe697-2db5-4a38-a759-1142a9655f6b.png">

**Comment by prumullertamas** [comment]
![erdeitemplom](https://user-images.githubusercontent.com/122269855/220090681-f0853a84-f2f0-4fa1-8098-92942532791f.jpg)

**Comment by prumullertamas** [comment]
![numbuh](https://user-images.githubusercontent.com/122269855/220100886-52a2b8e3-7b2d-453b-a91b-88b7c5ca0f94.png)
![numbers-2](https://user-images.githubusercontent.com/122269855/220100888-0cefdc90-9f8d-45f1-88e0-4f3bc5846a15.jpg)
![glowing-keyboard](https://user-images.githubusercontent.com/122269855/220100889-741d9fd2-01bf-4615-90ce-f410276e8c35.png)

Tess

**Comment by prumullertamas** [comment]
![onecalendar](https://user-images.githubusercontent.com/122269855/220101641-eaf32af1-79aa-40aa-a4ed-a03500ffe356.jpg)

**Comment by baracskaidora** [comment]
Carusel kész, méretre vágva, működik
